"""create jobs and job matches

Revision ID: 351be0dff288
Revises: e138bd76b721
Create Date: 2026-08-12 16:53:58.193866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '351be0dff288'
down_revision: Union[str, Sequence[str], None] = 'e138bd76b721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_job_id', name='uq_jobs_source_external_job_id')
    )
    op.create_index('ix_jobs_company_name', 'jobs', ['company_name'], unique=False)
    op.create_index('ix_jobs_is_active', 'jobs', ['is_active'], unique=False)
    op.create_index('ix_jobs_posted_at', 'jobs', ['posted_at'], unique=False)
    op.create_index('ix_jobs_source', 'jobs', ['source'], unique=False)
    op.create_index('ix_jobs_source_active', 'jobs', ['source', 'is_active'], unique=False)
    op.create_table('job_matches',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('title_score', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('location_score', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('remote_score', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('matched_skills', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('missing_required_skills', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('matched_roles', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('excluded_reasons', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', 'resume_id', name='uq_job_matches_job_user_resume')
    )
    op.create_index('ix_job_matches_decision', 'job_matches', ['decision'], unique=False)
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index('ix_job_matches_overall_score', 'job_matches', ['overall_score'], unique=False)
    op.create_index(op.f('ix_job_matches_resume_id'), 'job_matches', ['resume_id'], unique=False)
    op.create_index('ix_job_matches_user_created_at', 'job_matches', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_job_matches_user_decision', 'job_matches', ['user_id', 'decision'], unique=False)
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_index('ix_job_matches_user_decision', table_name='job_matches')
    op.drop_index('ix_job_matches_user_created_at', table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_resume_id'), table_name='job_matches')
    op.drop_index('ix_job_matches_overall_score', table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_index('ix_job_matches_decision', table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index('ix_jobs_source_active', table_name='jobs')
    op.drop_index('ix_jobs_source', table_name='jobs')
    op.drop_index('ix_jobs_posted_at', table_name='jobs')
    op.drop_index('ix_jobs_is_active', table_name='jobs')
    op.drop_index('ix_jobs_company_name', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
