"""create automation runs and logs

Revision ID: e138bd76b721
Revises: 1b1be28e21dd
Create Date: 2026-08-10 14:28:44.260513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e138bd76b721'
down_revision: Union[str, Sequence[str], None] = '1b1be28e21dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_succeeded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_run_type'), 'automation_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_automation_runs_status'), 'automation_runs', ['status'], unique=False)
    op.create_index(op.f('ix_automation_runs_user_id'), 'automation_runs', ['user_id'], unique=False)
    op.create_table('automation_logs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), server_default='info', nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_logs_entity_id'), 'automation_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_automation_logs_entity_type'), 'automation_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_automation_logs_event_type'), 'automation_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_automation_logs_level'), 'automation_logs', ['level'], unique=False)
    op.create_index(op.f('ix_automation_logs_occurred_at'), 'automation_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_automation_logs_run_id'), 'automation_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_automation_logs_status'), 'automation_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_logs_status'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_run_id'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_occurred_at'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_level'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_event_type'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_entity_type'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_entity_id'), table_name='automation_logs')
    op.drop_table('automation_logs')
    op.drop_index(op.f('ix_automation_runs_user_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_status'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_run_type'), table_name='automation_runs')
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
